@rinkebyhost = https://ethereum-api-staging.rarible.org
@ropstenhost = https://ethereum-api-dev.rarible.org
@mainnethost = https://ethereum-api.rarible.org
@localhost = http://localhost:8080
@hostname = {{rinkebyhost}}

### Encode order
POST {{hostname}}/v0.1/order/encoder/order
Content-Type: application/json

{
  "type": "RARIBLE_V2",
  "maker": "0xE1d7a59AB392EA29b059dAE31c5A573e2fEcC5A8",
  "taker": "0x0000000000000000000000000000000000000000",
  "make": {
    "assetType": {
      "assetClass": "ERC721",
      "contract": "0x04dCA48CBFd79287686F3Db03DC4EFEbC5266677",
      "tokenId": 1
    },
    "value": "1"
  },
  "take": {
    "assetType": {
      "assetClass": "ERC20",
      "contract": "0x350a9180ed984E12Fe6CfB244E2A86E6C51E17B1"
    },
    "value": "10000000000000000000"
  },
  "salt": 1,
  "start": 0,
  "end": 0,
  "data": {
    "dataType": "RARIBLE_V2_DATA_V1",
    "payouts": [
      {
        "account": "0x60f80121c31a0d46b5279700f9df786054aa5ee5",
        "value": 0
      }
    ],
    "originFees": [
      {
        "account": "0x60f80121c31a0d46b5279700f9df786054aa5ee5",
        "value": 0
      }
    ]
  },
  "signature": ""
}

### encode assettype
POST {{hostname}}/v0.1/order/encoder/assetType
Content-Type: application/json

{
  "assetClass": "ERC721",
  "contract": "0x60f80121c31a0d46b5279700f9df786054aa5ee5",
  "tokenId": 717802
}

### Encode order
POST {{hostname}}/v0.1/order/encoder/order
Content-Type: application/json

{
  "type": "RARIBLE_V2",
  "maker": "0x60f80121c31a0d46b5279700f9df786054aa5ee5",
  "taker": "0x60f80121c31a0d46b5279700f9df786054aa5ee5",
  "make": {
    "assetType": {
      "assetClass": "ERC721",
      "contract": "0xcfa14f6DC737b8f9e0fC39f05Bf3d903aC5D4575",
      "tokenId": "1"
    },
    "value": 717802
  },
  "take": {
    "assetType": {
      "assetClass": "ETH"
    },
    "value": 717802
  },
  "salt": 717802,
  "start": 0,
  "end": 0,
  "data": {
    "dataType": "RARIBLE_V2_DATA_V1",
    "payouts": [
      {
        "account": "0x60f80121c31a0d46b5279700f9df786054aa5ee5",
        "value": 0
      }
    ],
    "originFees": [
      {
        "account": "0x60f80121c31a0d46b5279700f9df786054aa5ee5",
        "value": 0
      }
    ]
  },
  "signature": "string"
}

### Encode
POST {{hostname}}/v0.1/order/encoder/order
Content-Type: application/json

{
    "type": "RARIBLE_V2",
    "maker": "0xa035F2A1fC34fec7EfbD2E9cA2d567c5Cc001d91",
    "make": {
        "assetType": {
            "assetClass": "ERC721",
            "contract": "0xcfa14f6DC737b8f9e0fC39f05Bf3d903aC5D4575",
            "tokenId": 1
        },
        "value": "1"
    },
    "take": {
        "assetType": {
            "assetClass": "ETH"
        },
        "value": "1000000000000000000"
    },
    "data": {
        "dataType": "RARIBLE_V2_DATA_V1",
        "payouts": [],
        "originFees": []
    },
    "salt": "3621",
    "signature": ""
}


### Sign Order
POST {{hostname}}/v0.1/order/orders
content-type: application/json

{
    "type": "RARIBLE_V2",
    "maker": "0x744222844bFeCC77156297a6427B5876A6769e19",
    "make": {
        "assetType": {
            "assetClass": "ERC721",
            "contract": "0xcfa14f6DC737b8f9e0fC39f05Bf3d903aC5D4575",
            "tokenId": 1
        },
        "value": "1"
    },
    "take": {
        "assetType": {
            "assetClass": "ETH"
        },
        "value": "1000000000000000000"
    },
    "data": {
        "dataType": "RARIBLE_V2_DATA_V1",
        "payouts": [],
        "originFees": []
    },
    "salt": "5422",
    "signature": "0x45461654b86e856686e7a2e9a9213b29f8dc32a731046e0c2f1aa01e4eaa991e41ebc67535fac14c333ad5b0d0d821ef518edc9ed08ad7efc0af572620c045ce1c"
}